# Generated by Django 2.1.7 on 2020-03-06 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busbooking',
            fields=[
                ('CSID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PH_NO', models.CharField(max_length=50)),
                ('USERNAME', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Busbooking',
                'verbose_name_plural': 'Busbookings',
            },
        ),
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('BID', models.AutoField(primary_key=True, serialize=False)),
                ('FROM', models.CharField(max_length=50)),
                ('TO', models.CharField(max_length=50)),
                ('BUSNAME', models.CharField(max_length=50)),
                ('BUSTIME', models.TimeField()),
                ('FARE', models.IntegerField()),
            ],
            options={
                'verbose_name': 'BusDetails',
                'verbose_name_plural': 'BusDetailss',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RID', models.IntegerField()),
                ('DATE', models.DateField(auto_now_add=True)),
                ('TIME', models.TimeField(auto_now_add=True)),
                ('BID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.BusDetails', verbose_name='BusDetails')),
                ('CSID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Busbooking', verbose_name='Busbooking')),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Registers',
            },
        ),
    ]
