# Generated by Django 2.1.7 on 2020-03-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='TOTAL_SEATS',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='register',
            name='Num_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='Total_Fare',
            field=models.FloatField(default=0),
        ),
    ]
